name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - name: Setup Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install prettytable matplotlib seaborn
      - name: build
        run: |
          source venv/bin/activate
          make build
      - name: install
        run: |
          source venv/bin/activate
          make install
      - name: test
        run: |
          source venv/bin/activate
          make test
      - name: claim-1
        run: make claim-1
      - name: claim-2
        run: make claim-2 SEEDS=10
      - name: Upload plots
        uses: actions/upload-artifact@v4
        with:
          name: plots-${{ matrix.os }}
          path: experiments/plots
