name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: python3 -m pip install prettytable matplotlib seaborn
      - name: build
        run: make build
      - name: install
        run: make install
      - name: test
        run: make test
      - name: claim-1
        run: make claim-1
      - name: claim-2
        run: make claim-2 SEEDS=10
      - name: Upload plots
        uses: actions/upload-artifact@v3
        with:
          name: plots-${{ matrix.os }}
          path: experiments/plots
